### ISSUE TITLE
Stheno is Zygote compatible

### ISSUE THREAD

**Issue by willtebbutt** [HamletWantToCode/GPFlux.jl#1]
The first line of GPFlux.jl's README is misleading regarding Stheno. In particular, it suggests that Stheno is incompatible with Flux and Zygote. 

This is not the case -- Stheno's introductory docs highlight this. Stheno specifically supports Zygote for it's reverse-mode AD and is, as a consequence, trivially compatible with Flux. I would suggest the README be re-worded to reflect this.

**Comment by nickrobinson251** [comment]
In fact Stheno may have even been the first ML package to use Zygote -- but anyway, yes, would be good to correct the Readme on this!

**Comment by HamletWantToCode** [comment]
Thank you for pointing out that @willtebbutt @nickrobinson251 :), I apologize for those misleading words, I have corrected my README file, hope this time is OK.

**Comment by willtebbutt** [comment]
No problem at all :) Thanks for sorting it out!
