### ISSUE TITLE
Motivation for additional GP package / opportunity to collaborate?

### ISSUE THREAD

**Issue by willtebbutt** [HamletWantToCode/GPFlux.jl#2]
It seems to me that we both have similar aims in a GP package. Stheno.jl is designed specifically with the intention of it being trivial to implement interesting and complicated kernels. AFAICT, the intention with GPFlux.jl is to make it possible to work with compositions of GPs and NN specified in Flux.

This is definitely straightforward to achieve in Stheno -- in particular my JuliaCon talk from last year included an example with a NN from Flux. I never got around to making a nice interface for people to hook into though, so it's something of a manual exercise at the minute.

I wonder whether it would be better for all involved for us to collaborate and extend Stheno's libary of mean functions and kernels with the stuff necessary to make it easier to use, rather than adding yet another GP package to the ecosystem? Is this something that you would be interested in doing @HamletWantToCode ?

**Comment by HamletWantToCode** [comment]
Hi @willtebbutt, you're right, it's good to have a unified GP framework, and I'm glad to contribute to Stheno.jl. GPFlux.jl is designed to make GP work seamlessly with Flux, there are some [requests](https://github.com/FluxML/Flux.jl/issues/433) on this. 

However, when I go through the docs and code of Stheno.jl, I can't find a working example that combines Stheno.jl with Flux.jl. Thank you for mentioning the JuliaCon talk, it would be nice if you could provide me with the code of "noisy sawtooth" example, then I can understand how Stheno works with Flux currently. 

If there is anything I could help, please let me know :)

**Comment by HamletWantToCode** [comment]
Also this [issue](https://github.com/STOR-i/GaussianProcesses.jl/issues/106) mention the need for a Flux compatible GP

**Comment by willtebbutt** [comment]
Great!

> However, when I go through the docs and code of Stheno.jl, I can't find a working example that combines Stheno.jl with Flux.jl

Good point. I'll make sure there's at least a low-level example in there combining the two. I'll find my noisy sawtooth code over the weekend and make it available.

**Comment by willtebbutt** [comment]
@HamletWantToCode I've raised an issue over on the Stheno repo. Perhaps we can continue this discussion there?

**Comment by HamletWantToCode** [comment]
OK, I will close this issue
